

runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  operating_system: ubuntu22


automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 7
  max_instances: 15